Ext.define('Siace.model.accounting.Plan_Contable', {
	extend: 'Ext.data.Model',
	idProperty: 'pctbl_id',

	fields: [
		{ name: 'pctbl_id', type: 'id' },
		{ name: 'pctbl_key', type: 'string' },
		{ name: 'pctbl_flga', type: 'string' },
		{ name: 'pctbl_cuenta', type: 'string' },
		{ name: 'pctbl_nombre', type: 'string' },
		{ name: 'pctbl_abrev', type: 'string' },
		{ name: 'tipcta_id', type: 'int' },
		{ name: 'tipanal_id', type: 'int' },
		{ name: 'tipanx_id', type: 'int' },
		{ name: 'tas_id', type: 'int' },
		{ name: 'regcta_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'pctbl_debe_mn', type: 'int' },
		{ name: 'pctbl_debe_me', type: 'int' },
		{ name: 'pctbl_haber_mn', type: 'int' },
		{ name: 'pctbl_haber_me', type: 'int' },
		{ name: 'pctbl_cencos', type: 'int' },
		{ name: 'pctbl_docref', type: 'int' },
		{ name: 'pctbl_fechaven', type: 'int' },
		{ name: 'pctbl_area', type: 'int' },
		{ name: 'pctbl_ctaaju', type: 'int' },
		{ name: 'pctbl_conban', type: 'int' },
		{ name: 'pctbl_docref2', type: 'int' },
		{ name: 'pctbl_tipmedpag', type: 'int' },
		{ name: 'pctbl_observ', type: 'string' },
		{ name: 'pctbl_estado', type: 'string' },
		
		{ name: 'tipcta_nombre', type: 'string' },
		{ name: 'tipcta_abrev', type: 'string' },
		{ name: 'tipcta_code', type: 'string' },
		{ name: 'tipanal_nombre', type: 'string' },
		{ name: 'tipanal_abrev', type: 'string' },
		{ name: 'tipanal_code', type: 'string' },
		{ name: 'tipanx_nombre', type: 'string' },
		{ name: 'tipanx_abrev', type: 'string' },
		{ name: 'tipanx_code', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'mone_code', type: 'string' },
	]
});