Ext.define('Siace.model.treasury.Bien_Serv', {
	extend: 'Ext.data.Model',
	idProperty: 'bs_id',

	fields: [
		{ name: 'bs_id', type: 'int' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bst_id', type: 'int' },
		{ name: 'bsg_id', type: 'int' },
		{ name: 'bsc_id', type: 'int' },
		{ name: 'bsf_id', type: 'int' },
		{ name: 'bscat_id', type: 'int' },
		{ name: 'bs_nombre' },
		{ name: 'bs_abrev', type: 'string' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'bs_code' },
		{ name: 'bsgest_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'bs_factor', type: 'string' },
		{ name: 'trib_id', type: 'int' },
		{ name: 'bs_monto', type: 'float' },
		{ name: 'bs_importe', type: 'float' },
		{ name: 'bs_inafecto', type: 'int' },
		{ name: 'bs_seeventa', type: 'int' },
		{ name: 'bs_cantid_min', type: 'float' },
		{ name: 'bs_cantid_max', type: 'float' },
		{ name: 'pctbl_id', type: 'int' },
		{ name: 'espedet_id', type: 'int' },
		{ name: 'fuefin_id', type: 'int' },
		{ name: 'bs_observ', type: 'string' },
		{ name: 'bs_estado', type: 'int' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'bs_gestion' },
		{ name: 'bst_code', type: 'string' },
		{ name: 'bst_nombre', type: 'string' },
		{ name: 'bsg_code', type: 'string' },
		{ name: 'bsg_nombre', type: 'string' },
		{ name: 'bsf_code', type: 'string' },
		{ name: 'bsf_nombre', type: 'string' },
		{ name: 'bscat_nombre', type: 'string' },
		{ name: 'bscat_abrev', type: 'string' },
		{ name: 'unimed_nombre', type: 'string' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'pctbl_cuenta', type: 'string' },
		{ name: 'pctbl_nombre', type: 'string' },
		{ name: 'espedet_nombre', type: 'string' },
		{ name: 'espedet_codigo', type: 'string' },
	]
});