Ext.define('Siace.model.treasury.Comprobante_Det', {
	extend: 'Ext.data.Model',
	idProperty: 'comprobdet_id',

	fields: [
		{ name: 'comprobdet_id', type: 'int' },
		{ name: 'comprobdet_key', type: 'string' },
		{ name: 'comprob_id', type: 'int' },
		{ name: 'comprobdet_item', type: 'int' },
		{ name: 'tablex', type: 'int' },
		{ name: 'tablex_id', type: 'int' },
		{ name: 'tabley', type: 'int' },
		{ name: 'tabley_id', type: 'int' },
		{ name: 'tippag_id', type: 'int' },
		{ name: 'pctbl_id', type: 'int' },
		{ name: 'espedet_id', type: 'int' },
		{ name: 'tablex_monto', type: 'float' },
		{ name: 'tablex_monto_pago', type: 'float' },
		{ name: 'tablex_monto_pago_real', type: 'float' },
		{ name: 'tipcamb_monto', type: 'float' },
		{ name: 'tipcamb_oper', type: 'int' },
		{ name: 'comprobdet_monto', type: 'float' },
		{ name: 'comprobdet_estado', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'comprob_key', type: 'string' },
		{ name: 'comprob_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'concp_id', type: 'int' },
		{ name: 'comprob_monto', type: 'float'},
		{ name: 'comprob_documento', type: 'string' },
		{ name: 'tippag_abrev', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'tablex_key', type: 'string' },
		{ name: 'tablex_documento', type: 'string' },
		{ name: 'tablex_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tabley_key', type: 'string' },
		{ name: 'pctbl_id', type: 'float' },
		{ name: 'espedet_id', type: 'float' },
		{ name: 'pctbl_cuenta', type: 'string' },
		{ name: 'pctbl_nombre', type: 'string' },
		{ name: 'debe_id', type: 'int' },
		{ name: 'debe_cuenta', type: 'string' },
		{ name: 'debe_nombre', type: 'string' },
		{ name: 'debe_monto', type: 'float' },
		{ name: 'haber_id', type: 'int' },
		{ name: 'haber_cuenta', type: 'string' },
		{ name: 'haber_nombre', type: 'string' },
		{ name: 'haber_monto', type: 'float' },
		{ name: 'espedet_codigo', type: 'string' },
		{ name: 'espedet_nombre', type: 'string' },
		{ name: 'espedet_monto', type: 'float' },
	]
});