Ext.define('Siace.model.treasury.Comprobante', {
	extend: 'Ext.data.Model',
	idProperty: 'comprob_id',

	fields: [
		{ name: 'comprob_id', type: 'int' },
		{ name: 'comprob_key', type: 'string' },
		{ name: 'sucr_id', type: 'int' },
		{ name: 'unieje_id', type: 'int' },
		{ name: 'year_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },		
		{ name: 'comprob_serie', type: 'int' },
		{ name: 'comprob_nro', type: 'int' },
		{ name: 'comprob_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipcomprob_id', type: 'int' },
		{ name: 'fuefin_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'comprob_monto', type: 'float' },
		{ name: 'comprob_observ', type: 'string' },
		{ name: 'comprob_estado', type: 'int' },
		{ name: 'comprob_documento', type: 'string' },
		{ name: 'tipcomprob_abrev', type: 'string' },
		{ name: 'tipcomprob_nombre', type: 'string' },
		{ name: 'entibanc_nombre', type: 'string' },
		{ name: 'cuebanc_key', type: 'string' },
		{ name: 'cuebanc_nrobanco', type: 'string' },
		{ name: 'cuebanc_nro', type: 'string' },
		{ name: 'fuefin_codename', type: 'string' },
		{ name: 'cuebancmov_nro', type: 'string' },
		{ name: 'cuebancmov_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'comprobespedet_monto', type: 'float' },
		{ name: 'comprobespedet_monto_igv', type: 'float' },
	]
});