Ext.define('Siace.model.treasury.Contrato', {
	extend: 'Ext.data.Model',
	idProperty: 'contr_key',

	fields: [
		{ name: 'contr_key', type: 'string' },
		{ name: 'contr_id', type: 'int' },
		{ name: 'contr_flga', type: 'string' },
		{ name: 'bscat_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'year_id', type: 'int' },
		{ name: 'mes_id', type: 'int' },
		{ name: 'contr_nro', type: 'int' },
		{ name: 'contr_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'contr_fechaini', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'contr_fechafin', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'contr_monto', type: 'float' },
		{ name: 'contr_pdf', type: 'string' },
		{ name: 'contr_observ', type: 'string' },
		{ name: 'contr_estado', type: 'int' },
		{ name: 'contr_documento' },
		{ name: 'bscat_nombre', type: 'string' },
		{ name: 'bscat_abrev', type: 'string' },		
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'unimed_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'tablex_fechaini', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tablex_fechafin', type: 'date', dateFormat: 'Y-m-d' },
	]
});