Ext.define('Siace.model.treasury.Cuenta_Bancaria', {
	extend: 'Ext.data.Model',
	idProperty: 'cuebanc_id',

	fields: [
		{ name: 'cuebanc_id', type: 'int' },
		{ name: 'cuebanc_key', type: 'string' },
		{ name: 'cuebanc_flga', type: 'string' },
		{ name: 'unieje_id', type: 'int' },
		{ name: 'entibanc_id', type: 'int' },
		{ name: 'tipcuebanc_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'cuebanc_nro', type: 'string' },
		{ name: 'cuebanc_abrev', type: 'string' },
		{ name: 'cuebanc_fechaini', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'cuebanc_fechafin', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'pctbl_id', type: 'int' },
		{ name: 'fuefin_id', type: 'int' },
		{ name: 'cuebanc_observ', type: 'string' },
		{ name: 'cuebanc_estado', type: 'int' },
		{ name: 'cuebanc_nrobanco', type: 'string' },
		{ name: 'entibanc_nombre', type: 'string' },
		{ name: 'entibanc_abrev', type: 'string' },
		{ name: 'entibanc_code', type: 'string' },
		{ name: 'tipcuebanc_nombre', type: 'string' },
		{ name: 'tipcuebanc_abrev', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'tipmone_id', type: 'int' },
		{ name: 'pctbl_cuenta', type: 'string' },
		{ name: 'pctbl_nombre', type: 'string' },
		{ name: 'fuefin_code', type: 'string' },
		{ name: 'fuefin_nombre', type: 'string' },
		{ name: 'fuefin_abrev', type: 'string' },
	]
});