Ext.define('Siace.model.treasury.Recibo', {
	extend: 'Ext.data.Model',
	idProperty: 'recib_id',

	fields: [
		{ name: 'recib_id', type: 'int' },
		{ name: 'recib_key', type: 'string' },
		{ name: 'recib_flga', type: 'string' },
		{ name: 'sucr_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'recib_serie', type: 'int' },
		{ name: 'recib_nro', type: 'int' },
		{ name: 'recib_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'concp_id', type: 'int' },
		{ name: 'tipdocident_id', type: 'int' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'tippag_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'recib_monto', type: 'float' },
		{ name: 'recib_observ', type: 'string' },
		{ name: 'espedet_id', type: 'int' },
		{ name: 'fuefin_id', type: 'int' },
		{ name: 'recib_observ', type: 'string' },
		{ name: 'recib_estado', type: 'int' },
		{ name: 'recib_documento', type: 'string' },
		{ name: 'concp_code', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'tippag_nombre', type: 'string' },
		{ name: 'tippag_abrev', type: 'string' },
		{ name: 'tablex_id', type: 'int' },
		{ name: 'tablex_key', type: 'string' },
		{ name: 'tablex_nro', type: 'string' },
		{ name: 'tablex_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tablex_monto', type: 'float' },
		{ name: 'tablex_documento', type: 'string' },
		{ name: 'tablex_detalle', type: 'string' },
	]
});