Ext.define("Siace.view.bud.EgresosB",{extend:"Siace.view.PanB",alias:["widget.bud_egreb"],items:[
{xtype:"panb1",title:"Módulo de Egresos Presupuestales ::.",width:"60%",items:[{xtype:"comp_grid",itemId:"grdBE",viewConfig:{getRowClass:function(r,rowI,rowP,str){return r.data.rcol;}},columns:[{xtype:"rownumberer",width:30},{dataIndex:"egre_documento",text:"Documento",width:85},{dataIndex:"egre_fecha",text:"Fecha",align:"center",renderer:fext_FD(),width:80},{dataIndex:"tipegre_abrev",text:"Tipo",width:50},{dataIndex:"secfunc_code",text:"S.F.",align:"center",width:45},{dataIndex:"tarea_codigo",text:"Tarea",align:"center",width:70},{dataIndex:"fuefin_code",text:"Rubro",width:40},{dataIndex:"area_abrev",text:"U.O.",width:60},{dataIndex:"expe_nro",text:"SIAF",align:"right",width:70},{dataIndex:"egre_monto",text:"Importe",align:"right",renderer:fext_FN(2),width:90},{dataIndex:"pers_nombre",text:"Razón Social",width:300}]}],
 dockedItems:[{xtype:"comp_cboopc"},
	{xtype:"comp_tooltop",items:[
		{xtype:"comppub_year_code"},{xtype:"comp_nrotop",itemId:"egre_nro"},{xtype:"comp_fechaini"},{xtype:"comp_fechafin"},{xtype:"comp_cbotop",itemId:"tipegre_id",valueField:"tabgen_id",displayField:"tabgen_code",tpl:"<tpl for='.'><div class='x-boundlist-item'>{tabgen_codename}&nbsp;</div></tpl>",fieldLabel:"&nbsp;Tipo",listConfig:{cls:"item00001",minWidth:160},width:50},{xtype:"comppub_area_abrev"},{xtype:"compbud_secfunc_code"},{xtype:"compbud_tarea_codigo"},
		{xtype:"container",layout:{type:"hbox"},items:[{xtype:"comp_cbotop",itemId:"tipdocident_id",name:"tipdocident_id",store:"array.TipDocIdentVentaAB",tpl:"<tpl for='.'><div class='x-boundlist-item'>{tipdocident_abrev}&nbsp;</div></tpl>",valueField:"tipdocident_id",displayField:"tipdocident_abrev",fieldLabel:"&nbsp;T.D.I.",listConfig:{cls:"item00001",minWidth:55},value:0,width:55},
			{xtype:"fieldcontainer",itemId:"cntPers",fieldLabel:"&nbsp;",labelAlign:"top",labelSeparator:"",layout:"hbox",items:[{xtype:"hiddenfield",itemId:"pers_key"},{xtype:"hiddenfield",itemId:"PERS_RUC"},{xtype:"comp_txttop",itemId:"pers_ruc",disabled:true,maxLength:11,width:90},{xtype:"comp_btn_imgsearch",itemId:"btnPPS",disabled:true},{xtype:"displayfield",itemId:"pers_nombre",hidden:true,fieldCls:"df00101"}]},
			{xtype:"fieldcontainer",itemId:"cntIndiv",fieldLabel:"&nbsp;",hidden:true,labelAlign:"top",labelSeparator:"",layout:"hbox",items:[{xtype:"hiddenfield",itemId:"indiv_key"},{xtype:"hiddenfield",itemId:"INDIV_DNI"},{xtype:"comp_txttop",itemId:"indiv_dni",disabled:true,maxLength:11,width:90},{xtype:"comp_btn_imgsearch",itemId:"btnPIS",disabled:true},{xtype:"displayfield",itemId:"indiv_apenom",hidden:true,fieldCls:"df00101"}]}
		]}
	]},
	{xtype:"comp_toolbtn",items:[{xtype:"comp_btnNew"},{xtype:"comp_btnModify"},{xtype:"comp_btnQuery"},{xtype:"comp_btnAnnular"},{xtype:"comp_btn",itemId:"btnSiaf",disabled:true,icon:"resources/icons/siaf.png",text:"SIAF"},{xtype:"comp_btnPrinter"},{xtype:"comp_btnFases",text:"Fases SIAF"}]},{xtype:"comp_pag",itemId:"pagBE"}
 ],__compPPS:null,setCompPPS:function(poComp){this.__compPPS=poComp;},getCompPPS:function(){return this.__compPPS;},__compPIS:null,setCompPIS:function(poComp){this.__compPIS=poComp;},getCompPIS:function(){return this.__compPIS;}
},
{xtype:"tpnb1",items:[
	{xtype:"tabb1",itemId:"tabBETF",title:"Detalle",items:[{xtype:"comp_grid",itemId:"grdBETF",columns:[{xtype:"rownumberer",width:30},{dataIndex:"area_abrev",text:"U.O.",sortable:false,width:60},{dataIndex:"tarea_codigo",text:"Tarea",sortable:false,width:70},{dataIndex:"espedet_codigo",text:"Clasificador",sortable:false,width:85},{dataIndex:"egretareafte_monto",text:"Importe",align:"right",renderer:fext_FN(2),width:90},{dataIndex:"espedet_nombre",text:"Descripción",sortable:false,width:300}]}],
	 dockedItems:[
		{xtype:"form",border:false,items:[{xtype:"comp_tooltop",defaults:{labelWidth:65},layout:"vbox",items:[{xtype:"container",layout:"hbox",items:[{xtype:"comp_dato",name:"egre_documento",fieldLabel:"Documento",labelWidth:65,width:180},{xtype:"comp_datofecha",name:"egre_fecha",fieldLabel:"Fecha",labelWidth:50}]},{xtype:"comp_dato",name:"tipegre_nombre",fieldLabel:"Tipo"},{xtype:"comp_dato",name:"area_nombre",fieldLabel:"U. Orgánica"},{xtype:"comp_dato",name:"secfunc_codename",fieldLabel:"Sec. Func."},{xtype:"comp_dato",name:"tarea_codename",fieldLabel:"Tarea Func."},{xtype:"comp_dato",name:"fuefin_codename",fieldLabel:"Rubro"}]}]},
		{xtype:"toolbar",dock:"bottom",margin:"-2 -6 -3 -6",ui:"footer",items:[{xtype:"comp_txtarea",itemId:"egre_observ",readOnly:true,rows:6,width:"100%"}]},{xtype:"comp_pag",itemId:"pagBETF",disabled:true}
	]},
	{xtype:"panel",itemId:"tabTE",height:"100%",hidden:true,layout:{type:"fit"},title:"Comprobantes",items:[
		{xtype:"comp_grid",itemId:"grdTE",columns:[{xtype:"rownumberer",width:30},{dataIndex:"egre_documento",text:"Documento",width:85},{dataIndex:"egre_fecha",text:"Fecha",align:"center",renderer:fext_FD(),width:80},{dataIndex:"egre_monto",text:"Importe",align:"right",renderer:fext_FN(2),width:90},{dataIndex:"cuebanc_nro",text:"Cta.Cte",width:120},{dataIndex:"cheq_nro",text:"Cheque",width:80}]}
	 ],
	 dockedItems:[{xtype:"comppub_menu",value:2129},{xtype:"comp_cboopc"},
	 	{xtype:"form",border:false,items:[{xtype:"comp_tooltop",defaults:{labelWidth:65},layout:"vbox",items:[{xtype:"container",layout:"hbox",items:[{xtype:"comp_dato",name:"egre_documento",fieldLabel:"Documento",labelWidth:65,width:180},{xtype:"comp_datofecha",name:"egre_fecha",fieldLabel:"Fecha",labelWidth:50}]},{xtype:"comp_dato",name:"tipegre_nombre",fieldLabel:"Tipo"},{xtype:"comp_dato",name:"area_nombre",fieldLabel:"U. Orgánica"},{xtype:"comp_dato",name:"secfunc_codename",fieldLabel:"Sec. Func."},{xtype:"comp_dato",name:"tarea_codename",fieldLabel:"Tarea Func."},{xtype:"comp_dato",name:"fuefin_codename",fieldLabel:"Rubro"}]}]},
		{xtype:"comp_toolbtn",items:[{xtype:"comp_btnNew"},{xtype:"comp_btnAnnular"},{xtype:"comp_btnPrinter"},{xtype:"comp_btn",itemId:"btnCheque",disabled:true,icon:"resources/icons/btnPrinter.png",text:"Cheque"},{xtype:"comp_btn",itemId:"btnHide",hidden:true}]},{xtype:"comp_pag",itemId:"pagTE",disabled:true}
	]}
]}]
});