Ext.define('Siace.model.operations.Guia', {
	extend: 'Ext.data.Model',
	idProperty: 'guia_id',

	fields: [
		{ name: 'guia_id', type: 'int' },
		{ name: 'guia_key', type: 'string' },
		{ name: 'guia_flga', type: 'string' },
		{ name: 'alma_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'guia_serie', type: 'int' },
		{ name: 'guia_nro', type: 'int'  },
		{ name: 'guia_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipdocident_id', type: 'int' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'transp_id', type: 'int' },
		{ name: 'indiv_id', type: 'int' },
		{ name: 'veh_id', type: 'int' },
		{ name: 'trac_id', type: 'int' },
		{ name: 'cont_id', type: 'int' },
		{ name: 'tipaux_id', type: 'int' },
		{ name: 'guia_code', type: 'string'  },
		{ name: 'guia_ing_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'guia_ing_hora' },
		{ name: 'guia_ing_usur_id', type: 'int' },
		{ name: 'guia_ing_peso', type: 'int' },
		{ name: 'guia_sal_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'guia_sal_hora' },
		{ name: 'guia_sal_usur_id', type: 'int' },
		{ name: 'guia_sal_peso', type: 'int' },
		{ name: 'guia_observ', type: 'string' },
		{ name: 'guia_estado', type: 'string' },
		{ name: 'guia_documento', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'perstransp_key', type: 'string' },
		{ name: 'perstransp_ruc', type: 'string' },
		{ name: 'perstransp_nombre', type: 'string' },
		{ name: 'perstransp_code', type: 'string' },
		{ name: 'veh_key', type: 'string' },
		{ name: 'veh_placa', type: 'string' },
		{ name: 'tipveh_placa', type: 'string' },
		{ name: 'trac_key', type: 'string' },
		{ name: 'trac_placa', type: 'string' },
		{ name: 'tractipveh_placa', type: 'string' },
		{ name: 'cont_key', type: 'string' },
		{ name: 'cont_placa', type: 'string' },
		{ name: 'tipaux_nombre', type: 'string' },
		{ name: 'regadua_documento', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'tablex_documento', type: 'string' },
		{ name: 'tablex_fecha', type: 'date', dateFormat: 'Y-m-d' },
	]
});