Ext.define('Siace.model.operations.Industria_Producto', {
	extend: 'Ext.data.Model',
	idProperty: 'indusprod_key',

	fields: [
		{ name: 'indusprod_key', type: 'string' },
		{ name: 'indusprod_flga', type: 'string' },
		{ name: 'indus_key', type: 'string' },
		{ name: 'indusprod_item', type: 'int' },
		{ name: 'bs_id', type: 'int' },
		{ name: 'indusprod_cantid', type: 'float' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre', type: 'string' },
		{ name: 'bs_abrev', type: 'string' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'indus_flga', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'indus_serie', type: 'int' },
		{ name: 'indus_aux', type: 'int' },
		{ name: 'indus_nro', type: 'int' },
		{ name: 'indus_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'indus_documento', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'bsalma_key', type: 'string' },
		{ name: 'bsalma_code', type: 'string' },
	]
});