Ext.define('Siace.model.operations.Industria_Insumo', {
	extend: 'Ext.data.Model',
	idProperty: 'indusinsu_key',

	fields: [
		{ name: 'indusinsu_key', type: 'string' },
		{ name: 'indusinsu_flga', type: 'string' },
		{ name: 'indusprod_id', type: 'int' },
		{ name: 'indusinsu_item', type: 'int' },
		{ name: 'bs_id', type: 'int' },
		{ name: 'indusinsu_estado' },
		{ name: 'indusinsu_cantid' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre' },
		{ name: 'bs_abrev' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'usur_login', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'indus_key', type: 'string' },
		{ name: 'indus_flga', type: 'string' },
		{ name: 'alma_id', type: 'int' },
		{ name: 'indus_serie', type: 'int' },
		{ name: 'indus_aux', type: 'int' },
		{ name: 'indus_numero', type: 'int' },
		{ name: 'indus_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'indus_documento', type: 'string' },
		{ name: 'bsalma_key', type: 'string' },
		{ name: 'bsalma_code', type: 'string' },
	]
});