Ext.define('Siace.model.operations.Industria_Coeficiente', {
	extend: 'Ext.data.Model',

	idProperty: 'induscoef_id',

	fields: [
		{ name: 'induscoef_id', type: 'int' },
		{ name: 'induscoef_key', type: 'string' },
		{ name: 'induscoef_flga', type: 'string' },
		{ name: 'indusinsu_id', type: 'int' },
		{ name: 'induscoef_item', type: 'int' },
		{ name: 'coef_item', type: 'int' },
		{ name: 'coef_id', type: 'int' },
		{ name: 'return_bs_id', type: 'int' },
		{ name: 'induscoef_cantid' },
		{ name: 'induscoef_cantid_return' },
		{ name: 'induscoef_estado', type: 'string' },
		{ name: 'coef_key', type: 'string' },
		{ name: 'coef_nombre', type: 'string' },
		{ name: 'coef_abrev', type: 'string' },
		{ name: 'tipcoef_id', type: 'int' },
		{ name: 'return_doc_id', type: 'int' },
		{ name: 'return_bs_key', type: 'string' },
		{ name: 'return_bs_code', type: 'string' },
		{ name: 'return_bs_nombre', type: 'string' },
		{ name: 'return_bs_abrev', type: 'string' },
		{ name: 'return_unimed_id', type: 'int' },
		{ name: 'return_nand_id', type: 'int' },
		{ name: 'return_bs_codigo', type: 'string' },
		{ name: 'return_unimed_nombre', type: 'string' },
		{ name: 'return_unimed_abrev', type: 'string' },
		{ name: 'return_marc_nombre', type: 'string' },
		{ name: 'return_marc_abrev', type: 'string' },
		{ name: 'return_mod_nombre', type: 'string' },
		{ name: 'return_mod_abrev', type: 'string' },
		{ name: 'return_nand_key', type: 'string' },
		{ name: 'return_nand_codigo', type: 'string' },
		{ name: 'indusinsu_key', type: 'string' },
		{ name: 'indusprod_id', type: 'int' },
		{ name: 'indusinsu_item', type: 'int' },
		{ name: 'indusinsu_bs_id', type: 'int' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre' },
		{ name: 'bs_abrev' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'indusprod_id', type: 'int' },
		{ name: 'indus_key', type: 'string' },
		{ name: 'indus_flga', type: 'string' },
		{ name: 'alma_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'indus_serie', type: 'int' },
		{ name: 'indus_aux', type: 'int' },
		{ name: 'indus_numero', type: 'int' },
		{ name: 'indus_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'indus_documento', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
	]
});