Ext.define('Siace.model.operations.Ingreso_Compra_Det', {
	extend: 'Ext.data.Model',
	idProperty: 'ingcompdet_key',

	fields: [
		{ name: 'ingcompdet_key', type: 'string' },
		{ name: 'ingcompdet_flga', type: 'string' },
		{ name: 'ingcomp_id', type: 'int' },
		{ name: 'ingcompdet_item', type: 'int' },
		{ name: 'bs_id', type: 'int' },
		{ name: 'ingcompdet_cantid', type: 'float' },
		{ name: 'ingcompdet_cantid_vobo', type: 'float' },
		{ name: 'ingcompdet_preuni', type: 'float' },
		{ name: 'ingcompdet_pretot', type: 'float' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'ingcompdetfase_fechaing' },
		{ name: 'ingcompdetfase_usur_id', type: 'int' },
		{ name: 'ingcompdet_estado', type: 'string' },
		{ name: 'ingcomp_key', type: 'string' },
		{ name: 'ingcomp_flga', type: 'string' },
		{ name: 'ingcomp_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ingcomp_documento', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'persimpor_ruc', type: 'string' },
		{ name: 'persimpor_nombre', type: 'string' },
		{ name: 'ing_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ing_documento', type: 'string' },
		{ name: 'ingdet_item', type: 'int' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre', type: 'string' },
		{ name: 'bs_abrev', type: 'string' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bsg_nombre', type: 'string' },
		{ name: 'bsc_nombre', type: 'string' },
		{ name: 'bsf_nombre', type: 'string' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre', type: 'string' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'fase_nombre', type: 'string' },
		{ name: 'fase_abrev', type: 'string' },
		{ name: 'fase_color', type: 'string' },
	]
});