Ext.define('Siace.model.operations.Ingreso_Compra', {
	extend: 'Ext.data.Model',
	idProperty: 'ingcomp_key',

	fields: [
		{ name: 'ingcomp_key', type: 'string' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'doc_tipo', type: 'string' },
		{ name: 'ingcomp_serie', type: 'string' },
		{ name: 'ingcomp_nro', type: 'string' },
		{ name: 'ingcomp_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'impor_id', type: 'int' },
		{ name: 'tippag_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'ingcomp_monto', type: 'float' },
		{ name: 'ingcomp_observ', type: 'string' },
		{ name: 'ingcomp_pdf', type: 'string' },
		{ name: 'ingcomp_estado', type: 'string' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'ingcompfase_fechaing' },
		{ name: 'ingcompfase_usur_id', type: 'int' },
		{ name: 'ingcompfase_observ', type: 'string' },
		{ name: 'ingcomp_documento', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'impor_key', type: 'string' },
		{ name: 'impor_ruc', type: 'string' },
		{ name: 'impor_nombre', type: 'string' },		
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'usur_login', type: 'string' },
		{ name: 'ingcompdet_rows', type: 'int' },
		{ name: 'ingcompdet_rows_vobo', type: 'int' },
		{ name: 'ingcompdet_cantids', type: 'float' },
		{ name: 'ingdet_rows', type: 'int' },
		{ name: 'ingdet_cantids', type: 'int' },
		{ name: 'ing_documento', type: 'string' },
	]
});