Ext.define('Siace.model.operations.Ingreso_Det', {
	extend: 'Ext.data.Model',
	idProperty: 'ingdet_key',

	fields: [
		{ name: 'ingdet_key', type: 'string' },
		{ name: 'ingdet_flga', type: 'string' },
		{ name: 'ingdet_item', type: 'int' },
		{ name: 'ingregadua_id', type: 'int' },
		{ name: 'ingcomp_id', type: 'int' },
		{ name: 'ingcompdet_item', type: 'int' },
		{ name: 'ingdet_cantid', type: 'float' },
		{ name: 'ingdet_preuni', type: 'float' },
		{ name: 'ingdet_pretot', type: 'float' },
		{ name: 'ingdet_peso', type: 'float' },
		{ name: 'ingdet_fleuni', type: 'float' },
		{ name: 'ingdet_seguni', type: 'float' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'ingdetfase_fechaing' },
		{ name: 'ingdetfase_usur_id', type: 'int' },
		{ name: 'ingdet_estado', type: 'string' },
		{ name: 'ingdet_compl', type: 'string' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre', type: 'string' },
		{ name: 'bs_abrev', type: 'string' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bsg_nombre', type: 'string' },
		{ name: 'bsc_nombre', type: 'string' },
		{ name: 'bsf_nombre', type: 'string' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre', type: 'string' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'fase_nombre', type: 'string' },
		{ name: 'fase_abrev', type: 'string' },
		{ name: 'fase_color', type: 'string' },
		{ name: 'ing_key', type: 'string' },
		{ name: 'ing_flga', type: 'string' },
		{ name: 'almalote_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'ing_serie', type: 'int' },
		{ name: 'ing_aux', type: 'int' },
		{ name: 'ing_nro', type: 'int' },
		{ name: 'ing_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipmov_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'ing_monto' },
		{ name: 'ing_monto_flete' },
		{ name: 'ing_monto_seguro' },
		{ name: 'ing_monto_cif' },
		{ name: 'ing_observ' },
		{ name: 'ing_estado', type: 'string' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'ingfase_fechaing' },
		{ name: 'ingfase_usur_id', type: 'int' },
		{ name: 'ingfase_observ', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'lote_key', type: 'string' },
		{ name: 'lote_nro', type: 'string' },
		{ name: 'lote_mzna', type: 'string' },
		{ name: 'lote_nombre', type: 'string' },
		{ name: 'bsalma_key', type: 'string' },
		{ name: 'bsalma_code', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'tipmov_nombre', type: 'string' },
		{ name: 'tipmov_abrev', type: 'string' },
		{ name: 'tipmov_code', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'ing_documento', type: 'string' },
		{ name: 'ingcomp_key', type: 'string' },
		{ name: 'ingcomp_serie' },
		{ name: 'ingcomp_nro' },
		{ name: 'ingcomp_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ingcomp_documento', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'regadua_key', type: 'string' },
		{ name: 'tipdocadua_id', type: 'int' },
		{ name: 'year_id', type: 'int' },
		{ name: 'adua_id', type: 'int' },
		{ name: 'aduaoper_id', type: 'int' },
		{ name: 'regadua_nro', type: 'string' },
		{ name: 'regadua_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'regadua_monto_seguro', type: 'float' },
		{ name: 'regadua_observ', type: 'string' },
		{ name: 'regadua_documento', type: 'string' },
		{ name: 'tipdocadua_nombre', type: 'string' },
		{ name: 'tipdocadua_abrev', type: 'string' },
		{ name: 'adua_nombre', type: 'string' },
		{ name: 'aduaoper_nombre', type: 'string' },
		{ name: 'persimpor_key', type: 'string' },
		{ name: 'persimpor_ruc', type: 'string' },
		{ name: 'persimpor_nombre', type: 'string' },
		{ name: 'regint_key', type: 'string' },
		{ name: 'regint_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'regint_monto_flete', type: 'float' },
		{ name: 'regint_documento', type: 'string' },
		{ name: 'guia_key', type: 'string' },
		{ name: 'guia_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'guia_documento', type: 'string' },
	]
});