Ext.define('Siace.model.operations.Ingreso', {
	extend: 'Ext.data.Model',
	idProperty: 'ing_id',

	fields: [
		{ name: 'ing_flga', type: 'string' },
		{ name: 'almalote_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'ing_serie' },
		{ name: 'ing_aux', type: 'int' },
		{ name: 'ing_nro' },
		{ name: 'ing_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipmov_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'ing_monto' },
		{ name: 'ing_monto_flete' },
		{ name: 'ing_monto_seguro' },
		{ name: 'ing_monto_cif' },
		{ name: 'ing_observ' },
		{ name: 'ing_estado', type: 'string' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'ingfase_fechaing' },
		{ name: 'ingfase_usur_id', type: 'int' },
		{ name: 'ingfase_observ', type: 'string' },
		{ name: 'ing_id', type: 'int' },
		{ name: 'ing_key', type: 'string' },
		{ name: 'ing_documento', type: 'string' },
		{ name: 'alma_key' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'lote_key' },
		{ name: 'lote_nro' },
		{ name: 'lote_mzna', type: 'string' },
		{ name: 'lote_nombre', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'tipmov_nombre', type: 'string' },
		{ name: 'tipmov_nombre02', type: 'string' },
		{ name: 'tipmov_abrev', type: 'string' },
		{ name: 'tipmov_code', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'usur_login', type: 'string' },
		{ name: 'ingdet_rows', type: 'int' },
		{ name: 'ingdet_rows_vobo', type: 'int' },
		{ name: 'ingdet_compl', type: 'int' },
		{ name: 'regadua_rows', type: 'int' },
		{ name: 'regadua_documento', type: 'string' },
	]
});