Ext.define('Siace.model.operations.Packing', {
	extend: 'Ext.data.Model',
	idProperty: 'pack_key',

	fields: [
		{ name: 'pack_key', type: 'string' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'pack_serie', type: 'string' },
		{ name: 'pack_nro', type: 'string' },
		{ name: 'pack_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'pack_observ', type: 'string' },
		{ name: 'pack_pdf', type: 'string' },
		{ name: 'pack_estado', type: 'string' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'packfase_fechaing' },
		{ name: 'packfase_usur_id', type: 'int' },
		{ name: 'packfase_observ', type: 'string' },
		{ name: 'pack_documento', type: 'string' },
		{ name: 'alma_key' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'pers_abrev', type: 'string' },
		{ name: 'usur_login', type: 'string' },
		{ name: 'packdet_rows', type: 'int' },
		{ name: 'packdet_rows_vobo', type: 'int' },
		{ name: 'packdet_cantids', type: 'float' },
	]
});