Ext.define('Siace.model.operations.Pedido', {
	extend: 'Ext.data.Model',
	idProperty: 'ped_id',

	fields: [
		{ name: 'ped_id', type: 'int' },
		{ name: 'ped_key', type: 'string' },
		{ name: 'ped_flga', type: 'string' },
		{ name: 'sucr_id', type: 'int' },
		{ name: 'unieje_id', type: 'int' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'ped_serie', type: 'int' },
		{ name: 'ped_nro', type: 'int' },
		{ name: 'ped_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'area_id', type: 'int' },
		{ name: 'tipdocident_id', type: 'int' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'oper_id', type: 'int' },
		{ name: 'unidveh_id', type: 'int' },
		{ name: 'lugserv_id', type: 'int' },
		{ name: 'ped_observ', type: 'string' },
		{ name: 'ped_estado', type: 'int' },
		{ name: 'ped_documento', type: 'string' },
		{ name: 'dic_id', type: 'int' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'oper_key', type: 'string' },
		{ name: 'oper_dni', type: 'string' },
		{ name: 'oper_apenom', type: 'string' },
		{ name: 'unidveh_redondeo', type: 'int' },
		{ name: 'veh_placa', type: 'string' },
		{ name: 'serv_id', type: 'int' },
		{ name: 'peddet_odoini', type: 'float', convert: null },
		{ name: 'peddet_odofin', type: 'float', convert: null },
		{ name: 'peddet_horoini', type: 'float', convert: null },
		{ name: 'peddet_horofin', type: 'float', convert: null },
		{ name: 'peddet_horaini', type: 'string' },
		{ name: 'peddet_horafin', type: 'string' },		
	]
});