Ext.define('Siace.model.operations.Salida', {
	extend: 'Ext.data.Model',
	idProperty: 'sal_id',

	fields: [
		{ name: 'sal_flga', type: 'string' },
		{ name: 'doc_id', type: 'int' },
		{ name: 'sal_serie' },
		{ name: 'sal_aux', type: 'int' },
		{ name: 'sal_nro' },
		{ name: 'sal_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipmov_id', type: 'int' },
		{ name: 'regadua_id', type: 'int' },
		{ name: 'pais_id', type: 'int' },
		{ name: 'comp_id', type: 'int' },
		{ name: 'pers_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'sal_monto' },
		{ name: 'sal_monto_cif' },
		{ name: 'sal_observ' },
		{ name: 'sal_estado', type: 'string' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'salfase_fechaing' },
		{ name: 'salfase_usur_id', type: 'int' },
		{ name: 'salfase_observ', type: 'string' },
		{ name: 'sal_key', type: 'string' },
		{ name: 'sal_id', type: 'integer' },
		{ name: 'sal_documento', type: 'string' },
		{ name: 'alma_key' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'lote_key' },
		{ name: 'lote_nro' },
		{ name: 'lote_mzna', type: 'string' },
		{ name: 'lote_nombre', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'tipmov_nombre', type: 'string' },
		{ name: 'tipmov_nombre02', type: 'string' },
		{ name: 'tipmov_abrev', type: 'string' },
		{ name: 'tipmov_code', type: 'string' },
		{ name: 'pais_nombre', type: 'string' },
		{ name: 'pais_code', type: 'string' },
		{ name: 'regadua_key', type: 'string' },
		{ name: 'regadua_flga', type: 'string' },
		{ name: 'tipdocadua_id', type: 'int' },
		{ name: 'year_id', type: 'int' },
		{ name: 'adua_id', type: 'int' },
		{ name: 'aduaoper_id', type: 'int' },
		{ name: 'regadua_nro', type: 'int' },
		{ name: 'regadua_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'regadua_monto_seguro', type: 'float' },
		{ name: 'regint_id', type: 'int' },
		{ name: 'transp_id', type: 'int' },
		{ name: 'regadua_observ', type: 'string' },
		{ name: 'regadua_estado', type: 'string' },
		{ name: 'regadua_documento', type: 'string' },
		{ name: 'comp_key', type: 'string' },
		{ name: 'comp_ruc', type: 'string' },
		{ name: 'comp_nombre', type: 'string' },
		{ name: 'pers_key', type: 'string' },
		{ name: 'pers_ruc', type: 'string' },
		{ name: 'pers_nombre', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'usur_login', type: 'string' },
		{ name: 'saldet_rows', type: 'int' },
		{ name: 'saldet_rows_vobo', type: 'int' },
	]
});