Ext.define('Siace.model.operations.Salida_Det', {
	extend: 'Ext.data.Model',
	idProperty: 'saldet_key',

	fields: [
		{ name: 'saldet_key', type: 'string' },
		{ name: 'saldet_flga', type: 'string' },
		{ name: 'saldet_item', type: 'int' },
		{ name: 'tablex_doc', type: 'int' },
		{ name: 'tablex_id', type: 'int' },
		{ name: 'tablex_item', type: 'int' },
		{ name: 'saldet_cantid', type: 'float' },
		{ name: 'saldet_preuni', type: 'float' },
		{ name: 'saldet_pretot', type: 'float' },
		{ name: 'saldet_cifuni', type: 'float' },
		{ name: 'saldet_ciftot', type: 'float' },
		{ name: 'fase_id', type: 'int' },
		{ name: 'saldetfase_fechaing' },
		{ name: 'saldetfase_usur_id', type: 'int' },
		{ name: 'saldet_estado', type: 'string' },
		{ name: 'sal_key', type: 'string' },
		{ name: 'sal_flga', type: 'string' },
		{ name: 'sal_serie', type: 'int' },
		{ name: 'sal_aux', type: 'int' },
		{ name: 'sal_nro', type: 'int' },
		{ name: 'sal_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'tipmov_id', type: 'int' },
		{ name: 'mone_id', type: 'int' },
		{ name: 'sal_monto_cif', type: 'float' },
		{ name: 'sal_documento', type: 'string' },
		{ name: 'alma_key', type: 'string' },
		{ name: 'alma_nombre', type: 'string' },
		{ name: 'alma_abrev', type: 'string' },
		{ name: 'alma_code', type: 'string' },
		{ name: 'lote_key', type: 'string' },
		{ name: 'lote_nro', type: 'string' },
		{ name: 'lote_mzna', type: 'string' },
		{ name: 'lote_nombre', type: 'string' },
		{ name: 'doc_nombre', type: 'string' },
		{ name: 'doc_abrev', type: 'string' },
		{ name: 'tipmov_nombre', type: 'string' },
		{ name: 'tipmov_abrev', type: 'string' },
		{ name: 'tipmov_code', type: 'string' },
		{ name: 'pais_nombre', type: 'string' },
		{ name: 'pais_code', type: 'string' },
		{ name: 'persimpor_key', type: 'string' },
		{ name: 'persimpor_ruc', type: 'string' },
		{ name: 'persimpor_nombre', type: 'string' },
		{ name: 'mone_nombre', type: 'string' },
		{ name: 'mone_abrev', type: 'string' },
		{ name: 'ing_key', type: 'string' },
		{ name: 'ing_flga', type: 'string' },
		{ name: 'ing_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ing_documento', type: 'string' },
		{ name: 'ingdet_item', type: 'int' },
		{ name: 'bs_key', type: 'string' },
		{ name: 'bs_code', type: 'string' },
		{ name: 'bs_nombre', type: 'string' },
		{ name: 'bs_abrev', type: 'string' },
		{ name: 'unimed_id', type: 'int' },
		{ name: 'nand_id', type: 'int' },
		{ name: 'bs_codigo', type: 'string' },
		{ name: 'unimed_nombre', type: 'string' },
		{ name: 'unimed_abrev', type: 'string' },
		{ name: 'marc_nombre', type: 'string' },
		{ name: 'marc_abrev', type: 'string' },
		{ name: 'mod_nombre', type: 'string' },
		{ name: 'mod_abrev', type: 'string' },
		{ name: 'nand_key', type: 'string' },
		{ name: 'nand_codigo', type: 'string' },
		{ name: 'ingcomp_key', type: 'string' },
		{ name: 'ingcomp_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ingcomp_documento', type: 'string' },
		{ name: 'regadua_key', type: 'string' },
		{ name: 'regadua_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'regadua_monto_seguro', type: 'float' },
		{ name: 'regadua_documento', type: 'string' },
		{ name: 'tipdocadua_nombre', type: 'string' },
		{ name: 'tipdocadua_abrev', type: 'string' },
		{ name: 'ingregadua_key', type: 'string' },
		{ name: 'ingregadua_fecha', type: 'date', dateFormat: 'Y-m-d' },
		{ name: 'ingregadua_monto_seguro', type: 'float' },
		{ name: 'ingregadua_documento', type: 'string' },

	]
});